
version: '3.8'

services:    
  database:
    image: postgres:alpine
    expose:
      - 5432
    ports:
      - 5432:5432
    container_name: 'pgsql'
    restart: always
    volumes:
      - .docker/postgresql:/var/lib/postgresql/data
    networks:
      - overlay
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestjs

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on: 
      - database
    networks:
      - overlay
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

networks:
  overlay:
    driver: bridge